version: "3.8"
services:
  postgres:
    container_name: postgres12
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
